#!/bin/bash

kubectl get event --watch &

until [[ "$(kubectl get helmrelease cortex '--output=go-template={{.status.releaseName}}')" = "cortex" ]]
do
	sleep 1
done

set -ex

kubectl wait helmrelease cortex --for=condition=Deployed
