apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: consul
spec:
  chart:
    spec:
      chart: consul
      version: 0.24.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  values:
    server:
      replicas: 1
      bootstrapExpect: 1
