apiVersion: v1
data:
  config.yaml: |
    alertmanager:
      replicas: 1
    distributor:
      replicas: 1
    ingester:
      replicas: 1
    ruler:
      replicas: 1
    querier:
      replicas: 1
    query_frontend:
      replicas: 1
    table_manager:
      replicas: 1
    configs:
      replicas: 1
    nginx:
      replicas: 1

    config:
      storage:
        cassandra:
          addresses: scylla-cluster-client
          port: 9042
          keyspace: cortex
          connect_timeout: 15s
          timeout: 15s
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cortex-config
