# According to https://docs.fluxcd.io/projects/helm-operator/en/stable/get-started/using-kustomize/
bases:
- ../../base
- github.com/SovereignCloudStack/k8s-minio/envs/ci-testing?ref=master
- github.com/SovereignCloudStack/k8s-cassandra/envs/ci-testing?ref=master
- github.com/fluxcd/helm-operator/deploy?ref=1.2.0

resources:
- cortex-config.yaml
- cortex-credentials.yaml

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: helm-operator
    namespace: flux
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
        - --enabled-helm-versions=v3
