apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: consul
spec:
  chart:
    repository: https://helm.releases.hashicorp.com
    name: consul
    version: 0.24.0
  wait: true
  values:
    name: consul
---
apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  ports:
  - name: http
    port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    app: consul
    component: server
