apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: hashicorp
spec:
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: consul
spec:
  interval: 1m
  chart:
    spec:
      chart: consul
      version: 0.24.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  values:
    name: consul
---
apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  ports:
  - name: http
    port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    app: consul
    component: server
