apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cortex
spec:
  chart:
    git: https://github.com/cortexproject/cortex-helm-chart.git
    path: .
    ref: 7b56da018b990fbe292c0a676ce553f0a91bd135
  wait: true
  valuesFrom:
  - configMapKeyRef:
      name: cortex-common-config
      key: config.yaml
  - configMapKeyRef:
      name: cortex-config
      key: config.yaml
  - secretKeyRef:
      name: cortex-credentials
      key: credentials.yaml
