apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cortex
spec:
  chart:
    git: https://github.com/cortexproject/cortex-helm-chart.git
    path: .
    ref: 0.1.2
  wait: true
  valuesFrom:
  - configMapKeyRef:
      name: cortex-upstream-default-config
      key: config.yaml
  - configMapKeyRef:
      name: cortex-common-config
      key: config.yaml
  - configMapKeyRef:
      name: cortex-config
      key: config.yaml
  - secretKeyRef:
      name: cortex-credentials
      key: credentials.yaml
